export type * from './announcement';
export type * from './article';
export type * from './auth';
export type * from './category';
export type * from './curriculum';
export type * from './facility';
export type * from './navigation';
export type * from './seo';
export type * from './ui';
